"""Create email_drafts table for AI-generated email drafts.

Stores drafts generated by the draft-email-v1 LLM endpoint when the
classifier suggests DRAFT_EMAIL. Each draft is linked to an
agent_suggestion and a scheduling loop/stage.
"""

from yoyo import step

step(
    """
    CREATE TABLE email_drafts (
        id                  TEXT PRIMARY KEY,
        suggestion_id       TEXT NOT NULL REFERENCES agent_suggestions(id),
        loop_id             TEXT NOT NULL REFERENCES loops(id),
        stage_id            TEXT NOT NULL REFERENCES stages(id),
        coordinator_email   TEXT NOT NULL,
        to_emails           TEXT[] NOT NULL,
        cc_emails           TEXT[] NOT NULL DEFAULT '{}',
        subject             TEXT NOT NULL,
        body                TEXT NOT NULL DEFAULT '',
        gmail_thread_id     TEXT,
        status              TEXT NOT NULL DEFAULT 'generated',
        sent_at             TIMESTAMPTZ,
        created_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
        updated_at          TIMESTAMPTZ NOT NULL DEFAULT now()
    );

    CREATE INDEX idx_drafts_suggestion
        ON email_drafts(suggestion_id);
    CREATE INDEX idx_drafts_coordinator_status
        ON email_drafts(coordinator_email, status);
    CREATE INDEX idx_drafts_loop
        ON email_drafts(loop_id);
    """,
    """
    DROP TABLE IF EXISTS email_drafts;
    """,
)
