"""Domain models for the scheduling agent."""

from __future__ import annotations

from enum import StrEnum
from typing import TYPE_CHECKING

from pydantic import BaseModel, Field

if TYPE_CHECKING:
    from api.gmail.models import Message
    from api.scheduling.models import (
        Candidate,
        ClientContact,
        Contact,
        Coordinator,
        Loop,
        LoopEvent,
    )


class EmailClassification(StrEnum):
    NEW_INTERVIEW_REQUEST = "new_interview_request"
    AVAILABILITY_RESPONSE = "availability_response"
    TIME_CONFIRMATION = "time_confirmation"
    RESCHEDULE_REQUEST = "reschedule_request"
    CANCELLATION = "cancellation"
    FOLLOW_UP_NEEDED = "follow_up_needed"
    INFORMATIONAL = "informational"
    UNRELATED = "unrelated"


class SuggestedAction(StrEnum):
    DRAFT_TO_RECRUITER = "draft_to_recruiter"
    DRAFT_TO_CLIENT = "draft_to_client"
    DRAFT_CONFIRMATION = "draft_confirmation"
    DRAFT_FOLLOW_UP = "draft_follow_up"
    REQUEST_NEW_AVAILABILITY = "request_new_availability"
    MARK_COLD = "mark_cold"
    CREATE_LOOP = "create_loop"
    ASK_COORDINATOR = "ask_coordinator"
    NO_ACTION = "no_action"


ACTIONS_REQUIRING_DRAFT: set[SuggestedAction] = {
    SuggestedAction.DRAFT_TO_RECRUITER,
    SuggestedAction.DRAFT_TO_CLIENT,
    SuggestedAction.DRAFT_CONFIRMATION,
    SuggestedAction.DRAFT_FOLLOW_UP,
    SuggestedAction.REQUEST_NEW_AVAILABILITY,
}


class SuggestionStatus(StrEnum):
    PENDING = "pending"
    ACCEPTED = "accepted"
    EDITED = "edited"
    REJECTED = "rejected"


class AgentContext(BaseModel):
    """Full context assembled for the agent to reason about."""

    model_config = {"arbitrary_types_allowed": True}

    new_message: Message
    thread_messages: list[Message]
    loop: Loop | None = None
    events: list[LoopEvent] = []
    coordinator: Coordinator
    recruiter: Contact | None = None
    client_contact: ClientContact | None = None
    candidate: Candidate | None = None


class ClassificationResult(BaseModel):
    """Output from the classification step."""

    classification: EmailClassification
    suggested_action: SuggestedAction
    confidence: float = Field(ge=0.0, le=1.0)
    reasoning: str
    questions: list[str] = []
    prefilled_data: dict | None = None  # for create_loop


class DraftEmail(BaseModel):
    """Email draft generated by the agent."""

    to: list[str]
    subject: str
    body: str
    in_reply_to: str | None = None


class AgentResult(BaseModel):
    """Complete agent output: classification + optional draft."""

    classification: ClassificationResult
    draft: DraftEmail | None = None
